version: '3.9'

services:
  php:
    image: php:8.1-fpm
    build:
      context: dockerfiles
      dockerfile: php.dockerfile
    container_name: ${APP_NAME:?app}-php
    volumes:
      - './src/${APP_DIR}:/var/www/app'
    networks:
      - app-net

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME:?err}-nginx
    ports:
      - '${NGINX_PORT}:80'
    links:
      - 'php'
    volumes:
      - './src/${APP_DIR}:/var/www/app'
      - './config/nginx:/etc/nginx/conf.d'
    networks:
      - app-net

  mariadb:
    image: mariadb:latest
    container_name: ${APP_NAME:?err}-mariadb
    restart: 'on-failure'
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-net

  redis:
    image: redis:latest
    container_name: ${APP_NAME:?err}-redis
    restart: unless-stopped
    ports:
      -  '${REDIS_PORT}:6379'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge